# Generated by Django 3.2.8 on 2021-10-20 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uk', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_de', models.CharField(max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_en', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_de', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uk', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_de', models.CharField(max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_en', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_de', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.SlugField(max_length=300, unique=True)),
            ],
            options={
                'verbose_name': 'ContentCategory',
                'verbose_name_plural': 'ContentCategories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=300, null=True)),
                ('article', models.CharField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('name_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('name_en', models.CharField(blank=True, max_length=300, null=True)),
                ('name_de', models.CharField(blank=True, max_length=300, null=True)),
                ('specification', models.CharField(blank=True, max_length=300, null=True)),
                ('advanced_description', models.TextField(blank=True, null=True, verbose_name='Advanced description')),
                ('is_active', models.BooleanField(default=1, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_en', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_de', models.CharField(blank=True, max_length=300, null=True)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_category', to='hort.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_product', models.CharField(blank=True, max_length=300, null=True)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hort.product')),
            ],
            options={
                'verbose_name': 'ProductImage',
                'verbose_name_plural': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.SlugField(max_length=300, unique=True)),
                ('published', models.BooleanField(default=0)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='content/main_image/')),
                ('title', models.CharField(max_length=300, null=True)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_uk', models.CharField(max_length=300, null=True)),
                ('title_en', models.CharField(max_length=300, null=True)),
                ('title_de', models.CharField(max_length=300, null=True)),
                ('full_text', models.TextField(null=True)),
                ('full_text_ru', models.TextField(null=True)),
                ('full_text_uk', models.TextField(null=True)),
                ('full_text_en', models.TextField(null=True)),
                ('full_text_de', models.TextField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_category', to='hort.contentcategory')),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
