# Generated by Django 3.2.8 on 2021-10-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0002_auto_20211020_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog_image/'),
        ),
    ]
