# Generated by Django 3.2.8 on 2021-11-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='source_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
