# Generated by Django 3.2.9 on 2021-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0005_applicability_cross_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='source_id',
            new_name='source_commercial',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='source_category',
            new_name='source_commercial',
        ),
        migrations.AddField(
            model_name='category',
            name='source_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
