# Generated by Django 3.2.9 on 2021-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0006_auto_20211118_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
