# Generated by Django 3.2.9 on 2021-11-18 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0007_product_source_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='source_commercial',
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uk', models.CharField(max_length=300, null=True)),
                ('name_en', models.CharField(max_length=300, null=True)),
                ('name_de', models.CharField(max_length=300, null=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_ru', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_uk', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_en', models.CharField(blank=True, max_length=300, null=True)),
                ('comment_de', models.CharField(blank=True, max_length=300, null=True)),
                ('url', models.SlugField(max_length=300, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='commercial_image/')),
                ('source_commercial', models.CharField(blank=True, max_length=300, null=True)),
                ('source_category', models.CharField(blank=True, max_length=300, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_category', to='hort.category')),
            ],
            options={
                'verbose_name': 'Commercial',
                'verbose_name_plural': 'Commercials',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='commercial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_commercial', to='hort.commercial'),
        ),
    ]
