# Generated by Django 4.0.1 on 2022-01-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0008_auto_20211118_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='advanced_description_de',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced description'),
        ),
        migrations.AddField(
            model_name='product',
            name='advanced_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced description'),
        ),
        migrations.AddField(
            model_name='product',
            name='advanced_description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced description'),
        ),
        migrations.AddField(
            model_name='product',
            name='advanced_description_uk',
            field=models.TextField(blank=True, null=True, verbose_name='Advanced description'),
        ),
    ]
