# Generated by Django 4.0.1 on 2022-01-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hort', '0009_product_advanced_description_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcategory',
            name='url',
        ),
    ]
